// Generated by CoffeeScript 1.4.0
(function() {

  global.node_env || (global.node_env = process.env.NODE_ENV || 'development');

  module.exports = require('./redis-message-capsule');

}).call(this);
